export const FETCHING_ARTISTS = 'FETCHING_ARTISTS';
export const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTISTS_SUCCESS';
export const FETCH_ARTISTS_FAIL = 'FETCH_ARTISTS_FAIL';

export const FETCHING_ALBUMS = 'FETCHING_ALBUMS';
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';
export const FETCH_ALBUMS_FAIL = 'FETCH_ALBUMS_FAIL';

export const FETCHING_SONGS = 'FETCHING_SONGS';
export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS';
export const FETCH_SONGS_FAIL = 'FETCH_SONGS_FAIL';
